language: android
android:
   components:
      - platform-tools

jdk:
   - openjdk8

beforce_install:
   - sudo apt-get -qq update
   - sudo apt-get install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev libesd0-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk2.8-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev -y
   - mkdir -p ~/bin
   - mkdir -p ~/android/lineage
   - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
   - chmod a+x ~/bin/repo
   - cd ~/android/lineage
   - repo init -u https://github.com/LineageOS/android.git -b cm-14.1

install:
   - ~/bin/repo sync
   - source build/envsetup.sh
   - breakfast wt88047
   - ./extract-files.sh
   - export USE_CCACHE=1
   - ccache -M 50G
   - export CCACHE_COMPRESS=1
   - export ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx4G"

script:
   - croot
   - brunch wt88047
